// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://loouyfusnadcgfltcxyt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxvb3V5ZnVzbmFkY2dmbHRjeHl0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNTg3MjMsImV4cCI6MjA2MDYzNDcyM30.3VdNPh2ycs04cHPBgZVPsKtn3fN6dPtlsgX7H4h8jZI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);